#server:
#  port: 8080
#
#mybatis:
#  mapper-locations: mapping/*.xml
#
#spring:
#  datasource:
#    name: miaosha
#    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 1028
#
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource